name: "Coral ML Inference"
version: "0.1.0"
slug: "coralml"
description: "Runs TensorFlow Lite models on the Coral USB Accelerator"
arch:
  - aarch64
  - armv7
  - amd64
startup: services
boot: auto
host_network: true

devices:
  - /dev/bus/usb:/dev/bus/usb:rwm

privileged:
  - SYS_ADMIN
  - SYS_RAWIO

options: {}
schema: {}
